# Generated by Django 4.2.1 on 2023-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('img', models.ImageField(upload_to='products/', verbose_name='изображение')),
                ('category', models.CharField(max_length=60, verbose_name='категория')),
                ('price_for_buy', models.IntegerField(verbose_name='цена за покупку')),
                ('creation_date', models.DateField(verbose_name='дата создания')),
                ('last_change_date', models.DateTimeField(verbose_name='дата последнего изменения')),
                ('first', models.CharField(max_length=70)),
            ],
        ),
    ]
